global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'fastapi'
  #   static_configs:
  #     - targets: ['192.168.1.15:8000']   # địa chỉ IP của máy host nếu FastAPI không chạy trong Docker

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:5001'] 